require("prototypes.item")
require("prototypes.recipe")
require("prototypes.tech")
require("prototypes.tank-entity")
require("prototypes.pole-entity")
require("prototypes.accu-entity")
require("prototypes.actuator-entity")
require("prototypes.itemsensor-entity")