require("prototypes.item")
require("prototypes.recipe")
require("prototypes.tech")
require("prototypes.common-entity")
require("prototypes.tank-entity")
require("prototypes.pump-entity")
require("prototypes.pole-entity")
require("prototypes.accu-entity")